### ISSUE TITLE
Write/Test endpoints manually with admin perms

### ISSUE THREAD

**Issue by elimelt** [swecc-uw/swecc-server#78]

**Comment by elimelt** [comment]
I'll be taking on message engagement endpoints:

`/engagement/message/`

**Comment by bhavik-soni** [comment]
I'll work on the attendance endpoints:
- POST engagement/attendance/attend
- GET engagement/attendance/session/{id}/
- GET engagement/attendance/member/{id}/
- GET engagement/attendance/
- POST engagement/attendance/session
